# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0002_foodjunction_menu_hungercycle_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodjunction_menu',
            name='foodPrice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hungercycle_menu',
            name='foodPrice',
            field=models.IntegerField(),
        ),
    ]
