# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0003_auto_20171110_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodjunction',
            name='name',
            field=models.CharField(max_length=5000),
        ),
    ]
